#ifndef __MAIN_H__
#define __MAIN_H__

#include "stm32f4xx.h"
//#include "sys.h"
#include "bsp.h"
#include "string.h"
#include "delay.h"
#include "usart1.h"	
#include "usart3.h"
#include "timer.h"
#include "led.h"
#include "key.h"
#include "can.h"
#include "can2.h"
#include "gun.h"
#include "laser.h" 
#include "mpu6050_i2c.h"
#include "mpu6050_interrupt.h"
#include "mpu6050_driver.h" 
#include "mpu6050_process.h"
#include "pid.h"
#include "GimbalMotor.h"
#include "buzzer.h"
#include "rc.h"
#include "ControlTask.h"
#include "CMControl.h"
#include "GimbalControl.h"
#include "IMUControl.h"
#include "RemoteControl.h"
#include "ShootControl.h"

#endif 
